// In-memory mock store — used when Supabase is not configured
import { SUPERSET_DATASOURCES, SUPERSET_FIELDS } from "@/lib/superset-seed";

export const mockStore = {
  knowledge_sources: [
    { id: "ks1", title: "Documentation Superset officielle", source_type: "documentation", content: "Guide officiel Superset pour la création de charts et dashboards.", url: "https://superset.apache.org/docs/", language: "Anglais", is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "ks2", title: "Guide interne Spacefill Superset", source_type: "guide_interne", content: "Comment utiliser Superset dans le contexte Spacefill : conventions de nommage, datasources disponibles.", url: null, language: "Français", is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  datasources: SUPERSET_DATASOURCES,
  fields_mapping: SUPERSET_FIELDS,
  chart_library: [
    // Dashboard: Réceptions
    { id: "c1", name: "Annonces de réceptions reçues", description: "Nombre d'annonces de réceptions reçues (big number)", datasource_id: "ds8", chart_type: "big_number", business_goal: "Suivre le volume d'annonces reçues sur la période", fields_used: ["order_reference", "created_at"], available_filters: ["Période", "Nom du client", "Transporteur"], use_cases: ["Suivi opérationnel réceptions", "Reporting client"], dashboards: ["Réceptions"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c2", name: "Réceptions complétées", description: "Nombre de réceptions terminées (big number)", datasource_id: "ds8", chart_type: "big_number", business_goal: "Mesurer le taux de complétion des réceptions", fields_used: ["status", "order_reference"], available_filters: ["Période", "Nom du client"], use_cases: ["KPI opérationnel", "Rapport de performance"], dashboards: ["Réceptions"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c3", name: "Répartition transport réception", description: "Répartition des modes de transport des réceptions (sunburst)", datasource_id: "ds8", chart_type: "sunburst", business_goal: "Analyser la part de chaque transporteur dans les réceptions", fields_used: ["carrier", "order_reference"], available_filters: ["Période", "Transporteur", "Client"], use_cases: ["Analyse logistique", "Négociation transporteurs"], dashboards: ["Réceptions"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c4", name: "Nombre total de réceptions", description: "Évolution du nombre de réceptions dans le temps (bar chart)", datasource_id: "ds8", chart_type: "bar", business_goal: "Visualiser l'évolution du volume de réceptions", fields_used: ["created_at", "order_reference"], available_filters: ["Période", "Client", "Transporteur"], use_cases: ["Analyse de tendance", "Reporting mensuel"], dashboards: ["Réceptions"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c5", name: "Suivi des réceptions des 7 derniers jours", description: "Tableau détaillé des réceptions sur la semaine glissante", datasource_id: "ds8", chart_type: "table", business_goal: "Suivre le détail des réceptions récentes", fields_used: ["order_reference", "status", "created_at", "carrier", "customer_name"], available_filters: ["Client", "Transporteur"], use_cases: ["Suivi quotidien", "Contrôle qualité"], dashboards: ["Réceptions"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    // Dashboard: KPIs Incidents
    { id: "c6", name: "Open Incidents", description: "Nombre total d'incidents ouverts (big number)", datasource_id: "ds7", chart_type: "big_number", business_goal: "Avoir une vue instantanée du nombre d'incidents actifs", fields_used: ["status", "id"], available_filters: ["Période", "Entrepôt", "Type d'incident"], use_cases: ["Monitoring qualité", "Escalade"], dashboards: ["KPIs Incidents"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c7", name: "Resolution Time", description: "Temps moyen de résolution des incidents (big number)", datasource_id: "ds7", chart_type: "big_number", business_goal: "Mesurer l'efficacité de traitement des incidents", fields_used: ["created_at", "resolved_at"], available_filters: ["Période", "Type d'incident"], use_cases: ["SLA", "Performance équipe"], dashboards: ["KPIs Incidents"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c8", name: "Incidents responsibility", description: "Répartition des incidents par responsabilité (pie chart)", datasource_id: "ds7", chart_type: "pie", business_goal: "Identifier qui est responsable des incidents (client, entrepôt, transporteur)", fields_used: ["responsibility", "id"], available_filters: ["Période", "Entrepôt"], use_cases: ["Analyse qualité", "Reporting client"], dashboards: ["KPIs Incidents"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c9", name: "Incidents per day", description: "Nombre d'incidents par jour (bar chart)", datasource_id: "ds7", chart_type: "bar", business_goal: "Détecter des pics d'incidents et des tendances", fields_used: ["created_at", "id"], available_filters: ["Période", "Type", "Entrepôt"], use_cases: ["Suivi opérationnel", "Détection anomalies"], dashboards: ["KPIs Incidents"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c10", name: "Incident Creator", description: "Répartition des incidents par créateur (pie chart)", datasource_id: "ds7", chart_type: "pie", business_goal: "Voir qui crée le plus d'incidents", fields_used: ["created_by", "id"], available_filters: ["Période"], use_cases: ["Analyse équipe", "Formation"], dashboards: ["KPIs Incidents"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c11", name: "Entry Orders - Incidents", description: "Nombre d'ordres d'entrée avec incidents (big number)", datasource_id: "ds10", chart_type: "big_number", business_goal: "Mesurer le taux d'incidents sur les entrées", fields_used: ["order_reference", "incident_count"], available_filters: ["Période", "Entrepôt"], use_cases: ["KPI qualité réceptions"], dashboards: ["KPIs Incidents"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    // Dashboard: Finance View — datasource exit_orders (sorties = ventes)
    { id: "c12", name: "Total ventes du mois", description: "Chiffre de ventes total du mois (big number)", datasource_id: "ds1", chart_type: "big_number", business_goal: "Suivre le CA mensuel en un coup d'oeil", fields_used: ["order_reference", "created_at"], available_filters: ["Période", "Entrepôt"], use_cases: ["Reporting finance", "Suivi objectifs"], dashboards: ["Demo \"Finance View\"", "Demo \"Manager View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c13", name: "Ventes par référence", description: "Tableau des ventes détaillées par référence produit", datasource_id: "ds1", chart_type: "table", business_goal: "Analyser les ventes produit par produit", fields_used: ["order_reference", "goods_type", "created_at"], available_filters: ["Période", "Entrepôt"], use_cases: ["Analyse produit", "Reporting commercial"], dashboards: ["Demo \"Finance View\"", "Demo \"Manager View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c14", name: "Variation de stock", description: "Évolution des sorties/entrées dans le temps (line chart)", datasource_id: "ds1", chart_type: "line", business_goal: "Visualiser les flux de stock et détecter les anomalies", fields_used: ["created_at", "order_reference", "goods_type"], available_filters: ["Entrepôt", "Période"], use_cases: ["Gestion stock", "Planification", "Finance"], dashboards: ["Demo \"Finance View\"", "Demo \"Logistic View\"", "Demo \"Manager View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    // Dashboard: Logistic View
    { id: "c15", name: "Approvisionnements de la journée", description: "Nombre d'approvisionnements du jour par statut (pie chart)", datasource_id: "ds8", chart_type: "pie", business_goal: "Vue instantanée des appros du jour", fields_used: ["status", "order_reference", "created_at"], available_filters: ["Entrepôt", "Statut"], use_cases: ["Suivi opérationnel quotidien"], dashboards: ["Demo \"Logistic View\"", "Demo \"Manager View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c16", name: "Approvisionnements en cours par source", description: "Tableau des approvisionnements en cours par source d'appro", datasource_id: "ds8", chart_type: "table", business_goal: "Identifier l'origine des approvisionnements actifs", fields_used: ["source", "status", "order_reference", "warehouse_ref"], available_filters: ["Source", "Entrepôt", "Statut"], use_cases: ["Suivi fournisseurs", "Logistique entrante"], dashboards: ["Demo \"Logistic View\"", "Demo \"Manager View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c17", name: "Approvisionnements par magasin", description: "Répartition des approvisionnements par entrepôt/magasin (bar chart)", datasource_id: "ds8", chart_type: "bar", business_goal: "Comparer le volume d'appros par site", fields_used: ["warehouse_ref", "order_reference", "created_at"], available_filters: ["Période", "Entrepôt", "Statut"], use_cases: ["Benchmark entrepôts", "Reporting ops"], dashboards: ["Demo \"Logistic View\"", "Demo \"Manager View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c18", name: "Nombre de demandes de réassort", description: "Volume de demandes de réassort sur les sorties (pie chart)", datasource_id: "ds12", chart_type: "pie", business_goal: "Mesurer la pression de réassort sur les stocks", fields_used: ["status", "order_reference"], available_filters: ["Période", "Entrepôt"], use_cases: ["Gestion stock", "Planification achats"], dashboards: ["Demo \"Logistic View\"", "Demo \"Manager View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: "c19", name: "Quantités demandées en réassort", description: "Volume total de quantités en demande de réassort (pie chart)", datasource_id: "ds12", chart_type: "pie", business_goal: "Quantifier les besoins de réassort", fields_used: ["gross_weight", "volume", "order_reference"], available_filters: ["Entrepôt", "Période"], use_cases: ["Planification achats", "Gestion ruptures"], dashboards: ["Demo \"Logistic View\""], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    // Dashboard: Transport
    { id: "c20", name: "Transport", description: "Évolution du volume transport par transporteur (bar chart)", datasource_id: "ds1", chart_type: "bar", business_goal: "Suivre et comparer les volumes par transporteur", fields_used: ["carrier", "created_at", "order_reference"], available_filters: ["Transporteur", "Période", "Entrepôt"], use_cases: ["Analyse transport", "Négociation tarifaire", "Performance transporteurs"], dashboards: ["Transport"], created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  dashboards: [
    { id: "dash1", title: "Réceptions", charts: ["c1","c2","c3","c4","c5"], created_at: new Date().toISOString() },
    { id: "dash2", title: "KPIs Incidents", charts: ["c6","c7","c8","c9","c10","c11"], created_at: new Date().toISOString() },
    { id: "dash3", title: 'Demo "Finance View"', charts: ["c12","c13","c14"], created_at: new Date().toISOString() },
    { id: "dash4", title: 'Demo "Logistic View"', charts: ["c14","c15","c16","c17","c18","c19"], created_at: new Date().toISOString() },
    { id: "dash5", title: 'Demo "Manager View"', charts: ["c12","c13","c14","c15","c16","c17","c18"], created_at: new Date().toISOString() },
    { id: "dash6", title: "Transport", charts: ["c20"], created_at: new Date().toISOString() },
  ],
  article_requests: [],
  generated_articles: [],
  feedbacks: [],
};

let nextId = 100;
export function newId() { return String(++nextId); }
